### ISSUE TITLE
Patch not working since Launcher updated

### ISSUE THREAD

**Issue by kneekick** [Lymia/MPPatch#51]
Following error on launch after installing the new launcher update 20.11.2018.

CivilizationV_DX11.exe - Fatal Application Exit
Cannot proxy CvGameDatabase! Original .dll file not found.

**Comment by Lymia** [comment]
I'm investigating.

**Comment by Lymia** [comment]
I've identified the issue. I'm working on fixing it.

**Comment by shmin2** [comment]
@Lymia Hello, have any updates on investigation?

**Comment by Lymia** [comment]
This issue has been fixed in the newest development release. You can download it here:
https://lymia.moe/jenkins/job/MPPatch/

**Comment by shmin2** [comment]
I tried on win10 with default installed Civ5, and now it's work.

Great job. Thank you.

**Comment by JavierCanon** [comment]
Hello, you can compile and make a release with the lasted bugfixes? thanks.

**Comment by SavageVictor** [comment]
Hello. Same issue on 0.1.2

**Comment by Lymia** [comment]
I'm going to be releasing a quick bugfix release soon, so I'm closing this for now.
