### ISSUE TITLE
Clicking Multiplayer on the Mod menu kicks back to menu

### ISSUE THREAD

**Issue by ValliteKing** [Lymia/MPPatch#54]
Whenever I try clicking on Multiplayer on the Mod menu, it brings up a "Configuring Game Files" and then it kicks me back to the main menu. Does it every time, even with the latest build. (0.1.3-Dev)

**Comment by DionSofiane** [comment]
I have the same problem, is there a way to fix it?

**Comment by Lymia** [comment]
I can't reproduce this bug. If someone can give me a log for when this happens, or more details about your system that might be causing this bug, that would be much appreciated.
