### ISSUE TITLE
Fatal Application Exit on Game Startup

### ISSUE THREAD

**Issue by FieryCharizard7** [Lymia/MPPatch#56]
After installing the patch, there is a Fatal Application Exit stating "Cannot proxy CvGameDatabase! Original .dll file not found.

**Comment by Lymia** [comment]
Try validating the game files in Steam then reinstalling MPPatch.

**Comment by FieryCharizard7** [comment]
@Lymia I believe this error is associated with  issue #51 about the new launcher. I used the 1.3 version on your website as mentioned in that issue thread and the patch works.

**Comment by Lymia** [comment]
ahha. I had forgotten how that issue manifests. I'll sit down properly sometime and properly do a 1.1 release. There's a lot of stuff I need to finish up.

Closing as a duplicate.
