### ISSUE TITLE
Crashing even without mod

### ISSUE THREAD

**Issue by FerdaneOgut** [Lymia/MPPatch#57]
Hi,

I tried to use the patch version mppatch-0.1.3-dev_12d05812 with my friend. It crashes after first turn. We even tried patch installed and without selecting any mod, it crashes. 
Anyone can help on this :/

**Comment by jaclo187** [comment]
Download lastest devbuild.
https://github.com/Lymia/MPPatch/issues/51#issuecomment-451692626

**Comment by Lymia** [comment]
I cannot reproduce this bug. If you have more information, such as a log or more information about your system that might have caused this, that would be much appreciated.
