### ISSUE TITLE
Inquiry: Beyond Earth compatibility?

### ISSUE THREAD

**Issue by VaelophisNyx** [Lymia/MPPatch#58]
Is this compatible at all given the amount of code similarities to Civ V? If not could it be made so?

**Comment by Lymia** [comment]
Oh shit. I'm under the impression that Beyond Earth was the first game to support online modded multiplayer officially, not Civ VI. 

From what I recall of me looking into the code, I'd think that it's still possible, but a bit harder. BE switches to Havok Script which is a different Lua VM, and will require me some more effort to figure out how to hook into properly.
