### ISSUE TITLE
Loading is stuck on "Changing patch package..."

### ISSUE THREAD

**Issue by JCFlipper** [Lymia/MPPatch#66]
When I try to run the .exe (I'm on windows) nothing happens apart from it making the mppatch_installer.log where it shows this below and just stops there. My friend has also run it and it has worked fine with no problems. (When he opens his it does the full loading information) and opens the installer.

I've restarted my PC, Redownloaded the file, I've downloaded civ, I've turned my antivirus off and done the same.

Any idea what could be causing this?

================================================================================
MPPatch version 0.1.3
Revision 8adb8b73, built on May 8, 2021 by jenkins@himawari

Build ID   : 3e5748f5-a000-46d0-87d3-cd86ca811320
Build Date : 2021-05-08T12:40:07Z
Revision   : 8adb8b735e884f26ae8e750339bbf213f8b556a4
Tree Status: <clean>
================================================================================

[2021-08-05T15:17:45Z/ INFO] Changing patch package...

**Comment by Lymia** [comment]
That is extremely strange. It looks like it fails to load entirely. Can you tell me anything about your system that might be unusual or different from your friend's? e.g. Windows version, edition, etc.

**Comment by JCFlipper** [comment]
Hey, thanks for the quick reply. 
Im on windows 10, the same as him. Version: 20H2. The only thing I can think of is that I don't have an activated version of windows? But I wouldn't expect that to affect anything, it's never messed with anything else before (just gives me the watermark in the corner).

**Comment by Lymia** [comment]
Yeah, that's unlikely to cause this. Do you have a normal copy of Civilization V? The next step that should be in the logs is where it checks for the installation location of the game, but this doesn't seem to have worked.

**Comment by JCFlipper** [comment]
As far as i'm aware its a normal copy, I tried verifying the files and when that didn't work I reinstalled civ but still had the same problem. 
And as for the installation location, the files are in the usual place,
Steam>steamapps>common> Sid Meier's Civilization V

**Comment by Lymia** [comment]
I'm guessing it's crashing trying to find your game directory, or something... I'm pretty sure that would have logged an error though. I legitimately don't know what the problem could be, sorry. I'll leave this open for when I have some more time to figure out what it could be.

**Comment by JCFlipper** [comment]
No worries, thank you for getting back to me so quickly. I'll try to mess around with it a bit more and see if I can figure it out. If not, I'll hopefully hear form you soon. Thanks a bunch

**Comment by IndieOK** [comment]
Any updates on this? having the exact same issue

**Comment by valrossenOliver** [comment]
Having same problem here. No error launching it from the console either.

**Comment by Lymia** [comment]
Do you two have similar logs to JCFlipper? (i.e. the last line logged is `Changing patch package...`. Unfortunately, I still don't have a great idea of how this would be possible, so I can't do anything immediately to fix it.

**Comment by IndieOK** [comment]
Yeah it's the exact same log. Closes after Changing patch package

**Comment by NihilEntropy** [comment]
Patch 0.1.2 works, 0.1.3 gives me the same issue as everyone else.

**Comment by NihilEntropy** [comment]
Ok found a weird fix, I ran the 0.1.2 exe version, patched, then downloaded both the 0.1.3 exe and jar. Then went back and opened the 0.1.2 version, enabled debug, reinstalled, then ran the jar version of 0.1.3, and it works.

**Comment by coolads934** [comment]
Having the same issue, stops at "Changing` patch package..."
although i cant install the 0.1.2 version either using the rar or exe, i get the error java.io.FileNotFoundException: mppatch_installer.log (Access is denied)
I also got this error message while trying the 0.1.3 versions jar file

**Comment by BlazeWarfaree** [comment]
i cannot get it to work either on my end stops at "Changing` patch package..."

**Comment by BlazeWarfaree** [comment]
wanted to mention this also happens with the jar version as well

================================================================================
MPPatch version 0.1.3
Revision 8adb8b73, built on May 8, 2021 by jenkins@himawari

Build ID   : 3e5748f5-a000-46d0-87d3-cd86ca811320
Build Date : 2021-05-08T12:40:07Z
Revision   : 8adb8b735e884f26ae8e750339bbf213f8b556a4
Tree Status: <clean>
================================================================================

[2021-11-30T06:51:11Z/ INFO] Changing patch package...

**Comment by BlazeWarfaree** [comment]
[DxDiag.txt](https://github.com/Lymia/MPPatch/files/7623556/DxDiag.txt) attached is my system specifications

**Comment by StardustGogeta** [comment]
This appears to be an issue with Java. Uninstalling all versions of Java and reinstalling the desired one fixed this exact issue for me.

**Comment by Biglulux** [comment]
I have the same issue with 0.1.3:
`================================================================================
MPPatch version 0.1.3
Revision 8adb8b73, built on May 8, 2021 by jenkins@himawari

Build ID   : 3e5748f5-a000-46d0-87d3-cd86ca811320
Build Date : 2021-05-08T12:40:07Z
Revision   : 8adb8b735e884f26ae8e750339bbf213f8b556a4
Tree Status: <clean>
================================================================================

[2022-03-25T23:57:43Z/ INFO] Changing patch package...`

I did exactly what @NihilEntropy recommended and I was able to update to 0.1.3 after installing 0.1.2.

**Comment by Silent-Whisper** [comment]
> 

you absolute genius I cannot believe how flawlessly that worked.

**Comment by Personwithhat** [comment]
Can confirm this issue - 

Have been pushing this in a Civ5 community for mod use.
Several members encountered this issue, uninstall all Java and installing just one version has successfully fixed the issue.

One of them commented that MPPatch is probably not correctly using "JAVA_HOME" or some such. And that same issue happens when using amazon coretto java, only works with Oracle java.

**Comment by Lymia** [comment]
This should no longer be an issue when 0.2.0 releases. I'm switching to using native-image over launch4j, and it will no longer require you to install Java at all.
