### ISSUE TITLE
Consider changing from LUAJit to a newer implementation.

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [Lymia/MPPatch#68]
I see that you are using LuaJIT but it seems that that project is kind of dead now. Because of that,I suggest considering another LuaJIT implementation that is actively being maintained. One I found is [RaptorJIT](https://github.com/raptorjit/raptorjit) but it may not be stable enough yet.

P.S: love the project. It is such an elegant solution to making Civ 5 run better without too much unnecessary fluff and making the multiplayer work.

**Comment by Lymia** [comment]
MPPatch uses a maintained branch of LuaJIT: https://github.com/openresty/luajit2/commits/v2.1-agentzh

It is more active than RaptorJIT, which had its last commit in 2019.

**Comment by TeaDrinkingProgrammer** [comment]
Oh, I didn't know that. Never mind then
