### ISSUE TITLE
Patch Windows version on Linux

### ISSUE THREAD

**Issue by Gudak0** [Lymia/MPPatch#70]
The native Linux version of Civ 5 has issues for me so I play the game via proton but I can't use the patcher to patch the windows version of the game and it will patch the native linux version of Civ 5 but as stated it doesn't work on my machine

**Comment by TeaDrinkingProgrammer** [comment]
That is normal behaviour. What happens with Proton is that it makes a Wine environment for each game which is seperate from the linux version. If you want to patch the proton version, you have to download the exe and launch it in that environment with Protontricks for example. You can follow the first part of [a guide I made](https://github.com/TeaDrinkingProgrammer/Civilization-V-Vox-Populi-on-Linux) for the vox populi mod.

**Comment by Lymia** [comment]
When I next get a chance to work on this, I might look into supporting Windows version on Linux. This is a particular use case I haven't thought of before. It should very much be possible.

**Comment by TeaDrinkingProgrammer** [comment]
> When I next get a chance to work on this, I might look into supporting Windows version on Linux. This is a particular use case I haven't thought of before. It should very much be possible to support.

Some background info: the reason for using the windows version, is that it runs better and more reliably since the linux port is quite old and has not been updated enough since. Put next to that that the windows version runs perfectly with proton and many people are recommending players to run the game through proton.

**Comment by ncanavan** [comment]
Supporting this would be very cool. Ive been playing from my Steam Deck and I use the win version as it runs better. I was able to apply the jar to the linux version but it doesn't get past the mods screen before crashing. Also want to say thanks for the patch, been using it for years!

**Comment by TeaDrinkingProgrammer** [comment]
So, now I've run into this problem myself: you can't open the exe in Proton because proton does not have Java...

**Comment by Gudak0** [comment]
don't use Proton to patch the game just install Java in regular wine and then use regular wine to patch the game

**Comment by TeaDrinkingProgrammer** [comment]
> don't use Proton to patch the game just install Java in regular wine and then use regular wine to patch the game

I have tried to install java in the wine prefix that proton was running in but that didn't work and I have read online that installing Java in Wine is quite tricky. Could you explain how  you succeeded? Did you use Lutris, bottles etc. and which installer did you use?

**Comment by Gudak0** [comment]
I'm pretty sure I ran the JDK installer in wine. No wine bottles, no lutris, just regular wine

**Comment by Gudak0** [comment]
double checked, JDK 8u251 installed with no issues. Wine staging 7.19

**Comment by Lymia** [comment]
I'll likely have a chance to work on this within the next week or two.

**Comment by resistancelion** [comment]
> I'll likely have a chance to work on this within the next week or two.

Can provide testing or remote desktop control, if you need

**Comment by Nocty1501** [comment]
Running `mppatch-0.1.3.exe` with protontricks and selecting Civ V does nothing... running it directly through wine doesn't help because it with the following message:

```
================================================================================
MPPatch version 0.1.3
Revision 8adb8b73, built on May 8, 2021 by jenkins@himawari

Build ID   : 3e5748f5-a000-46d0-87d3-cd86ca811320
Build Date : 2021-05-08T12:40:07Z
Revision   : 8adb8b735e884f26ae8e750339bbf213f8b556a4
Tree Status: <clean>
================================================================================

[2023-05-18T17:10:17Z/ INFO] Changing patch package...
Exception in thread "main" java.lang.NoSuchMethodError: Non-existent method WindowsRegOpenKey in java.util.prefs.WindowsPreferences was accessed.
        at moe.lymia.mppatch.util.win32.DynamicReflectiveProxy.applyDynamic(DynamicReflectiveProxy.scala:100)
        at moe.lymia.mppatch.util.win32.WindowsRegistry$.moe$lymia$mppatch$util$win32$WindowsRegistry$$withKey(WindowsRegistry.scala:37)
        at moe.lymia.mppatch.util.win32.WindowsRegistry$RegistryStringKey$.readKey(WindowsRegistry.scala:53)
        at moe.lymia.mppatch.util.win32.WindowsRegistry$Hive.readKey(WindowsRegistry.scala:72)
        at moe.lymia.mppatch.util.win32.WindowsRegistry$Hive.apply(WindowsRegistry.scala:73)
        at moe.lymia.mppatch.core.Win32Platform$.defaultSystemPaths(platform.scala:75)
        at moe.lymia.mppatch.ui.MainFrame.pathFromRegistry(MainFrame.scala:91)
        at moe.lymia.mppatch.ui.MainFrame.<init>(MainFrame.scala:102)
        at moe.lymia.mppatch.ui.InstallerMain.main(Installer.scala:77)
        at moe.lymia.mppatch.ui.Installer$.main(Installer.scala:89)
        at moe.lymia.mppatch.ui.Installer.main(Installer.scala)
```
