### ISSUE TITLE
No Multiplayer selection

### ISSUE THREAD

**Issue by Vinurinn** [Lymia/MPPatch#73]
When I install the mod, I don't get any errors, splash text on the menu is fine but when I load up my mods and want to open a MP game, I'm not able to choose multiplayer, only singleplayer. Anybody may know why?

Also I tried installing an older version, which just broke my CIV5 entirely and made me verify the integrity of the game files.

**Comment by TomeDrago** [comment]
I think it is problem with mods that have .dll files.....
So they are incompatible
Is there some workaround?

**Comment by Lymia** [comment]
I'll have to test with mods with DLL files. The approach I use *shouldn't* be incompatible with DLL mods, since it hooks the game in a different place - but it's worth investigating.

**Comment by TomeDrago** [comment]
I was testing on Gaia's Core Mod (v 312), maybe this will help. I don't have any other mods with .dll files other than this one.

**Comment by TomeDrago** [comment]
Is there somekind of walkaround for this problem?

> I'll have to test with mods with DLL files. The approach I use _shouldn't_ be incompatible with DLL mods, since it hooks the game in a different place - but it's worth investigating.

**Comment by GamerHawk121** [comment]
Was this figured out?

**Comment by TomeDrago** [comment]
> Was this figured out? I attempted this earlier in the day at the time of this posting so was curious is we can't use DLL mods with the MPPatch.

I don't think it was figured out
Still won't work for my with Gaia's Core
Did it work for you with other mods with dll?

**Comment by GamerHawk121** [comment]
> > Was this figured out? I attempted this earlier in the day at the time of this posting so was curious is we can't use DLL mods with the MPPatch.
> 
> I don't think it was figured out Still won't work for my with Gaia's Core Did it work for you with other mods with dll?

I went thru a few mids but they didn't contain a DLL shop I have no clue

**Comment by TomeDrago** [comment]
@Lymia maybe you have some kind of advice or quickfix that will not need you checking code?

**Comment by Korgi2** [comment]
@Lymia Me and my friend are having the same issue.

**Comment by klingonfunfunfun** [comment]
Same issue

I've posted some info in here
https://forums.civfanatics.com/threads/mppatch-easy-modded-multiplayer.617806/

Just need help finishing it off i.e. edit the EUI files so it fully works with MPPatch

* May not be same issue for everyone

**Comment by Lymia** [comment]
Likely duplicate of #53
