### ISSUE TITLE
Game Crashes On Startup - Arch Linux/EndeavourOS

### ISSUE THREAD

**Issue by Terraphice** [Lymia/MPPatch#82]
I tried installing this patch, and the game began crashing on startup. I tried to uninstall to begin testing, and it continues to crash on startup. Re-validating my files and clearing my cache don't fix the issue. Now in order to play, I have to use the Proton version of Civ V, which has some issues.

Running Civ5XP.launch gives me:
```
[Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198255149936 [API loaded no]
fish: Job 1, './Civ5XP.launch' terminated by signal SIGSEGV (Address boundary error)
```

There are no errors in the installer log for the patch, nor in the uninstall. Guess I'm going to have to dig around and find out what's been fucked up that can't be fixed via reinstall. Pretty high level issue for your program to cause. True uninstalls that put everything back the way they're supposed to be is the one thing most people consider a 'must' in the world of computer software.

Not sure what else to provide to help with this issue, let me know.

Software Version: Latest Release (Jar)

Game Version: Steam, Latest Release, Native Linux.

System Details:
OS: EndeavourOS [Arch Linux, essentially.]
DE: KDE (X11)
Shell: Fish (Dropped in from Bash w/ Bashrc.)
CPU: Ryzen 5 4600H
GPU: Nvidia GTX 1660Ti Mobile (Noveau Drivers)

(It's an Optimus system, but I don't use an Optimus manager and stick to only using the discrete GPU, the battery was removed previously and I use it like a desktop.)

**Comment by Lymia** [comment]
This is an issue with Civ V, not MPPatch, and I'm not sure I can fix it in a reasonable way.

Instead of setting it to the Proton version, try setting it to use the `Steam Linux Runtime 1.0 (scout)` in the Compatibility menu, which should solve this problem.

**Comment by Terraphice** [comment]
I tried it with both the Proton version and the native version multiple times...

**Comment by Lymia** [comment]
Does it work if you delete the Civilization V directory entirely and reinstall it? With no patch installed.
